name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Build
        run: |
          mkdir dist
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o dist/
      - name: Test
        run: |
          mkdir tmp
          make vet
          make test
  release:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Build
        run: |
          mkdir dist
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o dist/
          chmod +x dist/cidr
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cidr-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/cidr-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/cidr-${{ matrix.goos }}-${{ matrix.goarch }}
