name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: |
          mkdir dist
          go build -o dist/
          chmod +x dist/cidr
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cidr
          path: dist/cidr
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          name: v0.0.1
          files: dist/cidr
