name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.20.1"]
        os: ["ubuntu-22.04", "macos-12", "windows-2022"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: |
          mkdir dist
          make build
      - name: Test
        run: |
          mkdir tmp
          make vet
          make test
