name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.1"
      - name: Build
        run: |
          mkdir dist
          go build -ldflags "-s -w" -o dist/
      - name: Test
        run: |
          mkdir tmp
          make vet
          make test
