name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: |
          mkdir dist
          make build
      - name: Test
        run: |
          mkdir tmp
          make vet
          make test
